on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      release: ${{ steps.release.outputs }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          command: manifest
          default-branch: main
          monorepo-tags: true
      - run: echo "${{ toJSON(steps.release.outputs) }}"
        continue-on-error: true
      - if: ${{ steps.release.outputs['js--release_created'] }}
        run: echo "JS release created!"
      - if: ${{ steps.release.outputs['dotnet--release_created'] }}
        run: echo "Dotnet release created!"
      - if: ${{ steps.release.outputs['deeply/nested--release_created'] }}
        run: echo "Deeply nested release created!"
  next:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - run: echo ${{ needs.release.outputs.release }}
        continue-on-error: true
      - run: echo ${{ toJSON(needs.release.outputs.release) }}
        continue-on-error: true